### Get pokemon by name
GET {{localhost}}:{{port}}/api/v2/pokemon/ditto

### Save a favorite pokemon
POST {{localhost}}:{{port}}/api/v2/collection
Content-Type: application/json

{
  "pokemonName": "pikachu",
  "nickname": "Mein Starter 3"
}

> {%
    var res = response.body
    client.global.set("id", res.id)
%}

### Get all favorites
GET {{localhost}}:{{port}}/api/v2/collection

### Get pokemon by id
GET {{localhost}}:{{port}}/api/v2/collection/c3150679-0a3a-4a3b-a6cc-490b8c042e7b

### Delete pokemon by id
DELETE {{localhost}}:{{port}}/api/v2/collection/f314e94c-5398-49d2-b68d-56ff2ca0b475

### Update pokemon by id
PUT {{localhost}}:{{port}}/api/v2/collection/8097255c-6975-486a-b048-d023359a4803
Content-Type: application/json

{
  "nickname": "Mein neu Starter neu"
}