### Get pokemon by name
GET {{localhost}}:{{port}}/api/v2/pokemon/ditto

### Save a favorite pokemon
POST {{localhost}}:{{port}}/api/v2/collection
Content-Type: application/json

{
  "pokemonName": "pikachu",
  "nickname": "Mein Starter 3"
}

> {%
    var res = response.body
    client.global.set("id", res.id)
%}

### Get all favorites
GET {{localhost}}:{{port}}/api/v2/collection