### Get pokemon by name
GET {{localhost}}:{{port}}/api/v2/pokemon/ditto

### Save a favorite pokemon
POST {{localhost}}:{{port}}/api/collection
Content-Type: application/json

{
  "pokemonName": "clefairy",
  "nickname": "Mein Starter 2"
}

> {%
    var res = response.body
    client.global.set("id", res.id)
%}

### Get all favorites
GET {{localhost}}:{{port}}/api/collection

### Get pokemon by id
GET {{localhost}}:{{port}}/api/collection/{{id}}

### Delete pokemon by id
DELETE {{localhost}}:{{port}}/api/collection/{{id}}

### Update pokemon by id
PUT {{localhost}}:{{port}}/api/collection/{{id}}
Content-Type: application/json

{
  "nickname": "Mein neu Starter neu"
}